### ISSUE TITLE
Broken link in the Hacktoberfest contributor guideline

### ISSUE THREAD

**Issue by Arkaroy147** [meilisearch/.github#15]
The link in the hacktoberfest guideline takes us to a broken link
![Capture](https://user-images.githubusercontent.com/107761419/197964823-7d5270de-4f09-44f5-9cd7-5940e7d2de02.PNG)
Shall I change the link? Also, can you label this issue under hacktoberfest?

**Comment by CaroFG** [comment]
Closed by #16
